[template]
src   = "default.conf.tmpl"
dest  = "/conf/nginx/conf.d/default.conf"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/",
]
reload_cmd = "etcdctl set /services/nginx/reload reload"
